### PR TITLE
Make responsive

### PR DESCRIPTION
**Pull request by KennethAshley**
this PR updates the frontend to have:

- token icons
- responsiveness

### CODE REVIEW

**Comment by xenide** [comment]
Looks good. Was wondering if we want to get rid of the 'US$' and just have '$' since it's understood that it's US dollar anyway. Makes it slightly hard to read 

Or alternatively we can put the US$ in the column name.

**Comment by andersonaguiar** [comment]
Good stuff! As mentioned in the chat if we can just remove that top padding and also for the smallest screen (320px) fixing the overlapping numbers

image

**Review by OliverNChalk — APPROVED** [review]
I am unqualified to review this, however, it seems like you guys are hitting all the key usability concerns

**Comment by xenide** [comment]
Yup can confirm the US$ sign is gone. Thank you @KennethAshley!

**Review by xenide — APPROVED** [review]

**Pull request merged**
